### ISSUE TITLE
Handle nulls/upcoming interface changes properly

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#12]
Example from Kusto DL:

```
POST https://help.kusto.windows.net/v1/rest/query

Body:
{
    "db": "Samples",
    "properties": "{\"Options\":{\"response_dynamic_serialization\":\"json\", \"response_dynamic_serialization_2\":\"current\"}}",
    "csl": "print dynamic({\"a\":123}), dynamic(null)"
}
```

**Comment by alexkyllo** [comment]
It looks like the options for this property are "string" or "json", and I think the default is "json"?

What are our options on the R side for how to handle serialization of dynamic columns?

In my internal rkusto package, I coded it to always get the dynamic columns as JSON, and to pass those through as strings of JSON in R (and empty string "" in case of null), leaving it up to the user to parse them with fromJSON if they want.

But we could also handle that for the user and return in R a column of type 'list' (or NULL in case of empty list). Is that what you're thinking of doing?

**Comment by alexkyllo** [comment]
P.S. looks like the difference is "json" -> you get JSON, "string" -> you get serialized JSON in a string.

with "json":
```
"Rows": [
                [
                    {
                        "a": 123
                    },
                    null
                ]
            ]
```

with "string":
```
"Rows": [
                [
                    "{\"a\":123}",
                    "null"
                ]
            ]
```

**Comment by Hong-Revo** [comment]
Dunno, I'm just logging this as an issue right now.

**Comment by Hong-Revo** [comment]
Should be good enough for now
