### ISSUE TITLE
Implement prepared statements for parameterizing query strings

### ISSUE THREAD

**Issue by alexkyllo** [cloudyr/AzureKusto#13]
Currently if you want to build a KQL string to pass to [run_query](https://github.com/cloudyr/AzureKusto/blob/master/R/query.R#L9) you have to use string concatenation. We should implement a function that utilizes [kql-escape.R](https://github.com/cloudyr/AzureKusto/blob/master/R/kql-escape.R) to escape query parameters, akin to [glue_sql()](https://github.com/tidyverse/glue#glue_sql-makes-constructing-sql-statements-safe-and-easy) or [dbBind()](https://cran.r-project.org/web/packages/DBI/vignettes/spec.html#_bind_values_to_a_parameterizedprepared_statement_)

**Comment by Hong-Revo** [comment]
Looks like glue is actually pulled in by dplyr, so using it wouldn't add to our dependency footprint.

**Comment by alexkyllo** [comment]
In the meantime, here's a workaround:

```
> start = as.Date('2018-12-31')
> end = as.Date('2019-01-01')
> myFunction <- tbl_kusto(myDatabase, paste0("myFunction(", escape(start), ",", escape(end), ")"))
```
