### ISSUE TITLE
Implement ingestion endpoint

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#16]

**Comment by Hong-Revo** [comment]
There's at least 3 data sources we should support initially:

1. local file (*.csv)
2. blob storage
3. ingest from query

And 2 ways of doing so:

- streaming ingest REST API (handled by ingestion endpoint), which is for data source 1
- `.ingest` command (handled by query endpoint) which is for data sources 2 and 3

Data source 3 is also covered by #18.

Proposal: create `ingest_from_local` and `ingest_from_azure` functions to cover data sources 1 and 2. Former can either use the REST API (requires opening a support ticket while in preview) or per Python lib, upload the data to blob and then ingest from there.

@alexkyllo

**Comment by alexkyllo** [comment]
I think that, at least for now, `ingest_from_local` should do what the Python lib does--serialize the data to CSV, upload it to blob storage and ingest from there. We can use [AzureStor](https://github.com/cloudyr/AzureStor) to do this pretty easily, right? Then, after the upload to blob step, `ingest_from_local` can just call `ingest_from_azure`.

**Comment by Hong-Revo** [comment]
I've got them to enable streaming ingest on the dev cluster, so we can ingest locally or by uploading to blob. AzureStor can handle this, yes.

Also going to rename `kusto_query_endpoint` to `kusto_database_endpoint` and incorporate the streaming endpoint URI into the object. Ingestion looks like pretty messy with 2 endpoints and 3 methods involved, and we don't want to expose this externally.
