### ISSUE TITLE
Add write verbs such as compute() and copy_to()

### ISSUE THREAD

**Issue by alexkyllo** [cloudyr/AzureKusto#18]
The AzureKusto API currently only implements read operations. The dbplyr API also includes [compute](https://dplyr.tidyverse.org/reference/compute.html) for creating a table from the result of a query, and [copy_to](https://dplyr.tidyverse.org/reference/copy_to.html) for inserting R data into Kusto.

**Comment by alexkyllo** [comment]
It looks like dbplyr's implementation of `copy_to` uses `DBI::dbWriteTable` so since we now have an implementation of that method for Kusto, I'm planning to make use of it in implementing this verb.

Meanwhile, `compute` is the dbplyr equivalent of ingestion from a query. If I'm not mistaken, we don't have that implemented yet, so I'll need to add a function for it to `ingest.R` first, does that seem right @Hong-Revo ?

**Comment by Hong-Revo** [comment]
As I recall, you showed me that there's a dot-command to materialise a table, which is placed at the top of the whole pipeline (because of Kusto's wacky syntax where commands and queries are different). So `compute` could just use that. Shouldn't be too difficult.

**Comment by alexkyllo** [comment]
Yeah I guess I will just prepend `.set [TableName] <|` to the query and return a `tbl_kusto` instance that points to the new table. `.set` fails if the table already exists, which I think is what we want. dbplyr creates a temp table with a random name instead, but Kusto doesn't have temp tables.

**Comment by Hong-Revo** [comment]
closed in #45
