### ISSUE TITLE
Features needed for 1.0 Release?

### ISSUE THREAD

**Issue by alexkyllo** [cloudyr/AzureKusto#23]
Let's make a checklist of feature enhancements that we think are needed before we declare a 1.0 release and/or publish to CRAN.

Here are the ones I feel are important for feature-completeness:
- #13 query parameters, which I opened a PR for yesterday
- #16 ingestion endpoint
- #18 dplyr verbs for ingestion
- #24 support cross-cluster queries in dplyr API

**Comment by Hong-Revo** [comment]
Is cross-cluster joining that common?

**Comment by alexkyllo** [comment]
I run ad-hoc cross-cluster queries quite a bit. At least internally at Microsoft, it seems like every product team has their own Kusto cluster, so mashing up data across products requires either cross-cluster joins or writing ETL jobs (which means dropping down to Cosmos / Azure Data Lake and joining raw data in batch, and then perhaps copying the result to a new Kusto table).
