### ISSUE TITLE
Rename to AzureKusto?

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#3]
Per emails with internal Kusto team, and to be consistent with other OSS components:

https://github.com/Azure/azure-kusto-python
https://github.com/Azure/azure-kusto-node
https://github.com/Azure/azure-kusto-java

**Comment by Hong-Revo** [comment]
If we do rename, should probably do likewise for methods like `create_data_explorer`, `ade_database_endpoint` etc.

**Comment by Hong-Revo** [comment]
Well, for us the R bit will be superfluous since we're part of an R organization rather than Azure, and (hopefully) this will eventually be on CRAN as well.

I'm still a bit puzzled by how Kusto can be an internal name but also used for public-facing code, but that's a separate issue.

**Comment by alexkyllo** [comment]
Should we leave it as-is for now and wait until Kusto GA before making a name change? We can use repo tags to make it findable by either name.
________________________________

**Comment by alexkyllo** [comment]
I saw that e-mail thread--it's fine with me if you go ahead and change it to AzureKusto.
