### ISSUE TITLE
joining should not escape type of join

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#33]
In branch escape_ident: `inner_join(a, b)` produces `['a'] join kind = ['inner'] ['b']`; it should be `['a'] join kind = inner ['b']`

**Comment by Hong-Revo** [comment]
@alexkyllo is this correct? See also #32 .

**Comment by alexkyllo** [comment]
`inner` is a keyword rather than an identifier, so it shouldn't be escaped with [' ']
