### ISSUE TITLE
Join verbs failing in Kusto

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#36]
When the join verbs are used on actual Kusto tables, they result in the following error:

```r
ep <- kusto_database_endpoint(server, dbname, ...)
ir <- tbl_kusto(ep, "iris")
spec <- tbl_kusto(ep, "species")

out <- dplyr::left_join(ir, spec)
dplyr::collect(out)

# Error in UseMethod("op_vars") :
#   no applicable method for 'op_vars' applied to an object of class "character"
```

**Comment by Hong-Revo** [comment]
@alexkyllo can you take a look at this? `flatten_query` and/or `op_vars` doesn't seem to like operations that take 2 tables as inputs.

**Comment by alexkyllo** [comment]
Thanks for catching this. `flatten_query` was missing a base case when `x` is a character instead of a tbl_df, in the case where it's an `op_base_remote` rather than an `op_base_local`. Just pushed a one-liner fix to master.
