### ISSUE TITLE
Allow dynamic columns to be json

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#37]
Right now, dynamic cols have to be serialized as string; should also handle json. Might be tricky since the conversion from json to data.frame needs to know which bits to treat as rows and columns, and which are specific to a dynamic column.

**Comment by alexkyllo** [comment]
I was thinking that cells of R lists would be the natural way to deserialize a JSON column. Then we won't have to worry about which axis to tabulate the data along.

**Comment by Hong-Revo** [comment]
A list-column is the way to go, yes. However, `jsonlite::fromJSON` has a nifty feature where it can auto-convert tabular data into a data frame, and I'd like to keep using that if possible.

**Comment by Hong-Revo** [comment]
a35889ef8ce33039a4f0499f7c312efb63c484b3
