### ISSUE TITLE
Allow hints to be passed to join and summarise verbs

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#40]
Unlike SQL, KQL doesn't have query optimisation, so it's sometimes necessary to provide explicit hints on how joins are to be done.

**Comment by Hong-Revo** [comment]
@alexkyllo your thoughts? Is this something we should include?

**Comment by alexkyllo** [comment]
Yeah, it kind of breaks the abstraction but there are a lot of cases where a shuffle join or broadcast join is necessary for the query to finish, so I think we should make it available. It also applies to summarize.

**Comment by Hong-Revo** [comment]
The interface design I was thinking of would be to add this as an argument with a dot, eg `left_join(x, by=c("var1"="var2"), .strategy="broadcast")`. You could also extend this for cross-cluster joins with `.remote="left"` (or `"right"` etc).

I think I saw this in one of the dplyr verbs somewhere. It's also the approach I used in dplyrXdf, to let you specify the type of output to produce (data frame or Xdf file on disk).

**Comment by Hong-Revo** [comment]
aa87296df04af51bbe19ea7965df8cf5bea2b478
