### ISSUE TITLE
Add support for mv-expand operator

### ISSUE THREAD

**Issue by alexkyllo** [cloudyr/AzureKusto#48]
This is a Kusto-specific operator that expands array cells into rows. AzureKusto doesn't need to do anything other than define a dplyr-style function that translates to `| mv-expand <column name>`
https://docs.microsoft.com/en-us/azure/kusto/query/mvexpandoperator

**Comment by alexkyllo** [comment]
It looks like the dplyr verb to use for this is `unnest()`: https://tidyr.tidyverse.org/reference/unnest.html

**Comment by Hong-Revo** [comment]
a35889ef8ce33039a4f0499f7c312efb63c484b3
